version: "3.8"
services:
  kafka-to-hdfs-ingestion_service:
    build:
      context: ./kafka-to-hdfs-ingestion
      dockerfile: Dockerfile
    container_name: kafka-to-hdfs-ingestion_container

  spark_read_from_hdfs_service:
    build:
      context: ./spark_read_from_hdfs
      dockerfile: Dockerfile
    container_name: spark_read_from_hdfs_service_container
    depends_on:
      - kafka-to-hdfs-ingestion_service
