version: "3.8"
services:
  kafka-to-hdfs-ingestion:
    build:
      context: ./kafka-to-hdfs-ingestion
      dockerfile: Dockerfile
    image: helleberg/kafka-hdfs-ingester
    container_name: kafka-to-hdfs-ingestion_container

  spark-read-from-hdfs:
    build:
      context: ./spark-read-from-hdfs
      dockerfile: Dockerfile
    image: helleberg/spark-read-from-hdfs
    container_name: spark-read-from-hdfs-service_container
    depends_on:
      - kafka-to-hdfs-ingestion
