apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-forecast-data-avg-producer-autoscaler
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  schedule: "*/5 * * * *" # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: weather-forecast-data-avg-producer-autoscaler
            image: madswb/weather-forecast-data-avg-producer-autoscaler:latest
            imagePullPolicy: Always