apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-forecast-data-producer-autoscaler
spec:
  schedule: "*/5 * * * *" # Every 2 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: weather-forecast-data-producer-autoscaler
            image: madswb/weather-forecast-data-producer-autoscaler:latest
            imagePullPolicy: Always
          restartPolicy: OnFailure
